const PREFERRED_LANGUAGE_OPTIONS = [
  { label: "Thai", value: "Thai" },
  { label: "English", value: "English" },
  { label: "Chinese", value: "Chinese" },
  { label: "Japanese", value: "Japanese" },
  { label: "Burmese", value: "Burmese" },
  { label: "Lao", value: "Lao" },
  { label: "Other", value: "Other" },
];

const NATIONALITY_OPTIONS = [
  { label: "Thai", value: "Thai" },
  { label: "American", value: "American" },
  { label: "British", value: "British" },
  { label: "Chinese", value: "Chinese" },
  { label: "Japanese", value: "Japanese" },
  { label: "Korean", value: "Korean" },
  { label: "French", value: "French" },
  { label: "German", value: "German" },
  { label: "Australian", value: "Australian" },
  { label: "Indian", value: "Indian" },
  { label: "Other", value: "Other" },
];

export const FORM_ITEMS = [
  {
    label: "First Name",
    key: "firstName",
    inputType: "input",
    type: "text",
    required: true,
    placeholder: "Enter your first name",
    value: "",
    isFocused: false,
  },
  {
    label: "Middle Name",
    key: "middleName",
    inputType: "input",
    type: "text",
    required: false,
    placeholder: "Enter your middle name",
    value: "",
    isFocused: false,
  },
  {
    label: "Last Name",
    key: "lastName",
    inputType: "input",
    type: "text",
    required: true,
    placeholder: "Enter your last name",
    value: "",
    isFocused: false,
  },
  {
    label: "Date of Birth",
    key: "dob",
    inputType: "input",
    type: "date",
    required: true,
    placeholder: "dd/mm/yyyy",
    value: "",
    isFocused: false,
  },
  {
    label: "Gender",
    key: "gender",
    inputType: "select",
    type: "select",
    options: [
      { label: "Male", value: "male" },
      { label: "Female", value: "female" },
      { label: "Other", value: "other" },
    ],
    required: true,
    placeholder: "Enter your gender",
    value: "",
    isFocused: false,
  },
  {
    label: "Phone Number",
    key: "phoneNumber",
    inputType: "input",
    type: "tel",
    required: true,
    placeholder: "Enter your phone number",
    icon: "icon-phone.svg",
    value: "",
    isFocused: false,
  },
  {
    label: "Email",
    key: "email",
    inputType: "input",
    type: "email",
    required: true,
    placeholder: "Enter your email",
    icon: "icon-email.svg",
    value: "",
    isFocused: false,
  },
  {
    label: "Address",
    key: "address",
    inputType: "textarea",
    type: "text",
    required: true,
    placeholder: "Enter your address",
    icon: "icon-gps.svg",
    value: "",
    isFocused: false,
  },
  {
    label: "Preferred Language",
    key: "preferredLanguage",
    inputType: "select",
    type: "text",
    required: true,
    placeholder: "Enter your preferred language",
    options: PREFERRED_LANGUAGE_OPTIONS,
    icon: "icon-world.svg",
    value: "",
    isFocused: false,
  },
  {
    label: "Nationality",
    key: "nationality",
    inputType: "select",
    type: "text",
    required: true,
    placeholder: "Enter your nationality",
    options: NATIONALITY_OPTIONS,
    value: "",
    isFocused: false,
  },
  {
    label: "Contact Name",
    key: "contactName",
    inputType: "input",
    type: "text",
    required: false,
    placeholder: "Full Name",
    value: "",
    isFocused: false,
  },
  {
    label: "Relationship",
    key: "relationship",
    inputType: "input",
    type: "text",
    required: false,
    placeholder: "e.g. Spouse, Child, Parent, etc.",
    value: "",
    isFocused: false,
  },
  {
    label: "Religion",
    key: "religion",
    inputType: "input",
    type: "text",
    required: false,
    placeholder: "Enter your religion",
    value: "",
    isFocused: false,
  },
];
