export const FORM_ITEMS = [
  {
    label: "First Name",
    key: "firstName",
    inputType: "input",
    type: "text",
    required: true,
    placeholder: "Enter your first name",
  },
  {
    label: "Middle Name",
    key: "middleName",
    inputType: "input",
    type: "text",
    required: false,
    placeholder: "Enter your middle name",
  },
  {
    label: "Last Name",
    key: "lastName",
    inputType: "input",
    type: "text",
    required: true,
    placeholder: "Enter your last name",
  },
  {
    label: "Date of Birth",
    key: "dob",
    inputType: "input",
    type: "date",
    required: true,
    placeholder: "Enter your date of birth",
  },
  {
    label: "Gender",
    key: "gender",
    inputType: "select",
    type: "select",
    options: [
      { label: "Male", value: "male" },
      { label: "Female", value: "female" },
      { label: "Other", value: "other" },
    ],
    required: true,
    placeholder: "Enter your gender",
  },
  {
    label: "Phone Number",
    key: "phoneNumber",
    inputType: "input",
    type: "tel",
    required: true,
    placeholder: "Enter your phone number",
    icon: "icon-phone.svg",
  },
  {
    label: "Email",
    key: "email",
    inputType: "input",
    type: "email",
    required: true,
    placeholder: "Enter your email",
    icon: "icon-email.svg",
  },
  {
    label: "Address",
    key: "address",
    inputType: "textarea",
    type: "text",
    required: true,
    placeholder: "Enter your address",
    icon: "icon-gps.svg",
  },
  {
    label: "Preferred Language",
    key: "preferredLanguage",
    inputType: "select",
    type: "text",
    required: true,
    placeholder: "Enter your preferred language",
    options: [
      { label: "English", value: "English" },
      { label: "Thai", value: "Thai" },
    ],
    icon: "icon-world.svg",
  },
  {
    label: "Nationality",
    key: "nationality",
    inputType: "select",
    type: "text",
    required: true,
    placeholder: "Enter your nationality",
    options: [
      { label: "English", value: "English" },
      { label: "Thai", value: "Thai" },
    ],
  },
  {
    label: "Contact Name",
    key: "contactName",
    inputType: "input",
    type: "text",
    required: false,
    placeholder: "Full Name",
  },
  {
    label: "Relationship",
    key: "relationship",
    inputType: "input",
    type: "text",
    required: false,
    placeholder: "e.g. Spouse, Child, Parent, etc.",
  },
  {
    label: "Religion",
    key: "religion",
    inputType: "input",
    type: "text",
    required: false,
    placeholder: "Enter your religion",
  },
];
